font:
  family: Menlo
  size: 13.5
  use_thin_strokes: true

colors:
  cursor:
    cursor: '#abb2bf'

  primary:
    background: '#1c1c1c'
    foreground: '#ffffff'

  normal:
    black:   '#282c34'
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#d19a66'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#abb2bf'

  # Bright colors
  bright:
    black:   '#5c6370'
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#d19a66'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#ffffff'

window:
  padding:
    x: 15
    y: 10

selection:
  save_to_clipboard: true


dynamic_title: true
live_config_reload: true

key_bindings:
  - { key: Return, mods: Command, action: ToggleSimpleFullscreen }
  - { key: W,      mods: Command, action: Hide }
  - { key: N,      mods: Command, action: SpawnNewInstance }
